case class HotelBooking(
 bookingID: String,
 dateOfBooking: String,
 time: String,
 customerID: String,
 gender: String,
 age: Int,
 originCountry: String,
 state: String,
 location: String,
 destinationCountry: String,
 destinationCity: String,
 noOfVisitors: Int,
 checkInDate: String,
 noOfDays: Int,
 checkOutDate: String,
 rooms: Int,
 hotelName: String,
 hotelRating: Double,
 paymentMode: String,
 bankName: String,
 bookingPrice: Double,
 discount: Double,
 gst: Double,
 profitMargin: Double
)